// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "API to fetch hotel reviews and ratings.",
        "title": "Hotel Review API",
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {
        "/hotels/{hotel_id}/reviews": {
            "get": {
                "description": "Returns average rating and recent reviews for a hotel",
                "produces": ["application/json"],
                "tags": ["reviews"],
                "summary": "Get hotel reviews and overall rating",
                "parameters": [{
                    "type": "integer",
                    "name": "hotel_id",
                    "in": "path",
                    "required": true
                }],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    }
}`

func init() {
    swag.Register(swag.Name, &s{})
}

type s struct{}

func (s *s) ReadDoc() string {
    return docTemplate
}