name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  test:
    name: 🧪 Test & Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.8

    - name: Tidy & Lint
      run: |
        go mod tidy
        go fmt ./...
        go vet ./...

    - name: Run Unit Tests
      run: go test -v ./...

  build:
    name: 🛠 Build Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Docker Build
      run: docker build -t review-service:latest .

  push:
    name: 📦 Push Docker Image (Optional)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: |
        IMAGE=harshitanand/review-service
        TAG=${GITHUB_REF##*/}
        docker build -t $IMAGE:$TAG .
        docker push $IMAGE:$TAG

  deploy:
    name: 🚀 Deploy to Staging/Prod
    runs-on: ubuntu-latest
    needs: push
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull harshitanand/review-service:${GITHUB_REF##*/}
          docker stop review-service || true
          docker rm review-service || true
          docker run -d --name review-service -p 8080:8080 harshitanand/review-service:${GITHUB_REF##*/}
